question_data = [
    {"category": "Entertainment: Music",
     "type": "boolean", "difficulty": "medium",
     "question": "Arcade Fire&#039;s &#039;The Suburbs&#039; won the Album of the Year award in the 2011 Grammys.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Norwegian producer Kygo released a remix of the song &quot;Sexual Healing&quot; by Marvin Gaye.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "EDM label Monstercat signs tracks instead of artists.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "For his performance at ComplexCon 2016 in Long Beach, California, Skrillex revived his &quot;Mothership&quot; set piece for one night only.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Pink Guy&#039;s debut album was &quot;Pink Season&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Nick Mason is the only member to appear on every Pink Floyd album.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Musical artist, Future, collaborated with Kendrick Lamar for the song: &quot;Mask Off&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "A Facebook campaign placed Rage Against The Machine&#039;s &quot;Killing in the Name Of&quot; as the UK Christmas Number 1 in 2009.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "Metallica collaborated with Rowan Atkinson&#039;s Mr Bean on a 1992 comic relief single.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
     "question": "&quot;Neutral Milk Hotel&quot; is a real band.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
